[phases.setup]
aptPkgs = [
    "libpango-1.0-0",
    "libpangocairo-1.0-0",
    "libgdk-pixbuf2.0-0",
    "shared-mime-info",
    "fonts-liberation",
]

[phases.build]
cmds = ["python manage.py collectstatic --noinput"]
