[phases.setup]
nixPkgs = [
    "glib",
    "pango",
    "cairo",
    "gdk-pixbuf",
    "fontconfig",
    "freetype",
    "fribidi",
    "harfbuzz",
    "libpng",
    "zlib",
    "shared-mime-info",
]

[phases.build]
cmds = ["python manage.py collectstatic --noinput"]
