# Generated by Django 5.2.16 on 2026-07-19 10:47

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PTARubricHead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, max_length=10)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'PTA Rubric Head',
                'verbose_name_plural': 'PTA Rubric Heads',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=255)),
                ('name_fr', models.CharField(blank=True, max_length=255)),
                ('logo', models.ImageField(blank=True, upload_to='schools/logos/')),
                ('seal', models.ImageField(blank=True, upload_to='schools/seals/')),
                ('matricule', models.CharField(max_length=50, unique=True)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('region_en', models.CharField(max_length=255)),
                ('region_fr', models.CharField(blank=True, max_length=255)),
                ('division_en', models.CharField(max_length=255)),
                ('division_fr', models.CharField(blank=True, max_length=255)),
                ('motto_en', models.CharField(default='Peace - Work - Fatherland', max_length=255)),
                ('motto_fr', models.CharField(default='Paix - Travail - Patrie', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'School',
                'verbose_name_plural': 'Schools',
            },
        ),
        migrations.CreateModel(
            name='PTARubricSubHead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, max_length=10)),
                ('rubric_head', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_heads', to='core.ptarubrichead')),
            ],
            options={
                'verbose_name': 'PTA Rubric Sub-Head',
                'verbose_name_plural': 'PTA Rubric Sub-Heads',
            },
        ),
        migrations.AddField(
            model_name='ptarubrichead',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pta_rubric_heads', to='core.school'),
        ),
        migrations.CreateModel(
            name='FeeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('PTA', 'PTA'), ('state', 'State')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_types', to='core.school')),
            ],
            options={
                'verbose_name': 'Fee Type',
                'verbose_name_plural': 'Fee Types',
            },
        ),
        migrations.CreateModel(
            name='ConductThreshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conduct_type', models.CharField(choices=[('warning', 'Conduct Warning'), ('reprimand', 'Reprimand'), ('suspension', 'Suspension'), ('dismissal', 'Dismissal')], max_length=20, unique=True)),
                ('min_unjustified_abs', models.PositiveIntegerField(default=0)),
                ('min_justified_abs', models.PositiveIntegerField(default=0)),
                ('min_lateness', models.PositiveIntegerField(default=0)),
                ('min_punishment_hours', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conduct_thresholds', to='core.school')),
            ],
            options={
                'verbose_name': 'Conduct Threshold',
                'verbose_name_plural': 'Conduct Thresholds',
            },
        ),
        migrations.CreateModel(
            name='AcademicTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term_number', models.PositiveSmallIntegerField(choices=[(1, 'First Term'), (2, 'Second Term'), (3, 'Third Term')])),
                ('year_start', models.PositiveIntegerField()),
                ('year_end', models.PositiveIntegerField()),
                ('is_current', models.BooleanField(default=False)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='core.school')),
            ],
            options={
                'verbose_name': 'Academic Term',
                'verbose_name_plural': 'Academic Terms',
                'unique_together': {('school', 'term_number', 'year_start', 'year_end')},
            },
        ),
        migrations.CreateModel(
            name='SchoolClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(help_text='e.g., F1, F2, LS, US', max_length=20)),
                ('stream', models.CharField(blank=True, help_text='e.g., A, B, Industrial, Commercial', max_length=50)),
                ('cycle', models.CharField(choices=[('first', 'First Cycle'), ('second', 'Second Cycle')], default='first', max_length=10)),
                ('promotion_mark', models.FloatField(default=10.0)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='core.school')),
            ],
            options={
                'verbose_name': 'Class',
                'verbose_name_plural': 'Classes',
                'ordering': ['sort_order'],
                'unique_together': {('school', 'code', 'stream')},
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('other_names', models.CharField(blank=True, max_length=255)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('unique_id', models.CharField(help_text='9-digit state ID', max_length=9, unique=True, validators=[django.core.validators.MinLengthValidator(9)])),
                ('repeater', models.BooleanField(default=False)),
                ('date_of_birth', models.DateField()),
                ('place_of_birth', models.CharField(max_length=255)),
                ('guardian_name', models.CharField(max_length=255)),
                ('guardian_contact', models.CharField(blank=True, max_length=50)),
                ('guardian_address', models.TextField(blank=True)),
                ('division_of_origin', models.CharField(max_length=255)),
                ('region_of_origin', models.CharField(max_length=255)),
                ('father_name', models.CharField(blank=True, max_length=255)),
                ('mother_name', models.CharField(blank=True, max_length=255)),
                ('parent_contact', models.CharField(blank=True, max_length=50)),
                ('photo', models.ImageField(blank=True, upload_to='students/photos/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='core.school')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'ordering': ['first_name', 'other_names'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(help_text='e.g., ENL, FRE, MAT', max_length=10)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='core.school')),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
                'ordering': ['sort_order'],
                'unique_together': {('school', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Competency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competencies', to='core.academicterm')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competencies', to='core.subject')),
            ],
            options={
                'verbose_name': 'Competency',
                'verbose_name_plural': 'Competencies',
                'ordering': ['subject', 'sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('signature', models.ImageField(blank=True, upload_to='teachers/signatures/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='core.school')),
            ],
            options={
                'verbose_name': 'Teacher',
                'verbose_name_plural': 'Teachers',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Punishment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.DecimalField(decimal_places=1, max_digits=5)),
                ('reason', models.TextField()),
                ('date_given', models.DateField()),
                ('academic_term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='punishments', to='core.academicterm')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='punishments', to='core.student')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.teacher')),
            ],
            options={
                'verbose_name': 'Punishment',
                'verbose_name_plural': 'Punishments',
            },
        ),
        migrations.CreateModel(
            name='IncomeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date_paid', models.DateField()),
                ('receipt_number', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('academic_term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.academicterm')),
                ('fee_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='income_records', to='core.feetype')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='income_records', to='core.school')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='income_records', to='core.student')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.teacher')),
            ],
            options={
                'verbose_name': 'Income Record',
                'verbose_name_plural': 'Income Records',
                'ordering': ['-date_paid'],
            },
        ),
        migrations.CreateModel(
            name='ExpenditureRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('PTA', 'PTA'), ('state', 'State')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('academic_term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.academicterm')),
                ('rubric_sub_head', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenditure_records', to='core.ptarubricsubhead')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenditure_records', to='core.school')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.teacher')),
            ],
            options={
                'verbose_name': 'Expenditure Record',
                'verbose_name_plural': 'Expenditure Records',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_registers', to='core.schoolclass')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.teacher')),
            ],
            options={
                'verbose_name': 'Attendance Register',
                'verbose_name_plural': 'Attendance Registers',
                'unique_together': {('school_class', 'date')},
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('superuser', 'Superuser'), ('admin', 'Administrator'), ('bursar', 'Bursar'), ('class_master', 'Class Master'), ('teacher', 'Teacher')], default='teacher', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profiles', to='core.school')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
        migrations.AlterUniqueTogether(
            name='ptarubrichead',
            unique_together={('school', 'code')},
        ),
        migrations.CreateModel(
            name='FinanceSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_pta_income', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_pta_expenditure', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_state_income', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_state_expenditure', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finance_summaries', to='core.academicterm')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finance_summaries', to='core.school')),
            ],
            options={
                'verbose_name': 'Finance Summary',
                'verbose_name_plural': 'Finance Summaries',
                'unique_together': {('school', 'academic_term')},
            },
        ),
        migrations.CreateModel(
            name='PTADueConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pta_due_configs', to='core.school')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pta_due_configs', to='core.schoolclass')),
            ],
            options={
                'verbose_name': 'PTA Due Config',
                'verbose_name_plural': 'PTA Due Configs',
                'unique_together': {('school', 'school_class')},
            },
        ),
        migrations.CreateModel(
            name='DisciplineSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unjustified_abs_hours', models.DecimalField(decimal_places=1, default=0, max_digits=6)),
                ('justified_abs_hours', models.DecimalField(decimal_places=1, default=0, max_digits=6)),
                ('lateness_count', models.PositiveIntegerField(default=0)),
                ('punishment_hours', models.DecimalField(decimal_places=1, default=0, max_digits=6)),
                ('conduct_decision', models.CharField(blank=True, choices=[('warning', 'Conduct Warning'), ('reprimand', 'Reprimand'), ('suspension', 'Suspension'), ('dismissal', 'Dismissal')], max_length=20)),
                ('academic_term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discipline_summaries', to='core.academicterm')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discipline_summaries', to='core.student')),
            ],
            options={
                'verbose_name': 'Discipline Summary',
                'verbose_name_plural': 'Discipline Summaries',
                'unique_together': {('student', 'academic_term')},
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('P', 'Present'), ('AJ', 'Absent Justified'), ('AU', 'Absent Unjustified'), ('L', 'Late')], max_length=2)),
                ('register', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='core.attendanceregister')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='core.student')),
            ],
            options={
                'verbose_name': 'Attendance Record',
                'verbose_name_plural': 'Attendance Records',
                'unique_together': {('register', 'student')},
            },
        ),
        migrations.CreateModel(
            name='StudentEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_enrolled', models.DateField(auto_now_add=True)),
                ('academic_term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='core.academicterm')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='core.schoolclass')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='core.student')),
            ],
            options={
                'verbose_name': 'Student Enrollment',
                'verbose_name_plural': 'Student Enrollments',
                'unique_together': {('student', 'academic_term')},
            },
        ),
        migrations.CreateModel(
            name='ClassSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coefficient', models.PositiveSmallIntegerField(default=1)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='core.schoolclass')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_subjects', to='core.subject')),
            ],
            options={
                'verbose_name': 'Class Subject',
                'verbose_name_plural': 'Class Subjects',
                'ordering': ['sort_order'],
                'unique_together': {('school_class', 'subject')},
            },
        ),
        migrations.CreateModel(
            name='SubjectAverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average', models.DecimalField(decimal_places=2, max_digits=5)),
                ('grade', models.CharField(blank=True, max_length=5)),
                ('remark', models.CharField(blank=True, max_length=50)),
                ('academic_term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_averages', to='core.academicterm')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_averages', to='core.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_averages', to='core.subject')),
            ],
            options={
                'verbose_name': 'Subject Average',
                'verbose_name_plural': 'Subject Averages',
                'unique_together': {('student', 'subject', 'academic_term')},
            },
        ),
        migrations.CreateModel(
            name='CompetencyScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('date_recorded', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competency_scores', to='core.academicterm')),
                ('competency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='core.competency')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competency_scores', to='core.student')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.teacher')),
            ],
            options={
                'verbose_name': 'Competency Score',
                'verbose_name_plural': 'Competency Scores',
                'unique_together': {('student', 'competency', 'academic_term')},
            },
        ),
        migrations.CreateModel(
            name='TeacherAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_class_master', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='core.schoolclass')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='core.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='core.teacher')),
            ],
            options={
                'verbose_name': 'Teacher Assignment',
                'verbose_name_plural': 'Teacher Assignments',
                'unique_together': {('teacher', 'school_class', 'subject')},
            },
        ),
        migrations.CreateModel(
            name='TermResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_score', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('total_coef', models.PositiveSmallIntegerField(default=0)),
                ('average', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('rank', models.PositiveIntegerField(blank=True, null=True)),
                ('grade', models.CharField(blank=True, max_length=5)),
                ('remark', models.CharField(blank=True, max_length=50)),
                ('remark_on_performance', models.TextField(blank=True)),
                ('promoted', models.BooleanField(blank=True, null=True)),
                ('academic_term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='term_results', to='core.academicterm')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='term_results', to='core.student')),
            ],
            options={
                'verbose_name': 'Term Result',
                'verbose_name_plural': 'Term Results',
                'unique_together': {('student', 'academic_term')},
            },
        ),
    ]
