# Generated by Django 5.2.16 on 2026-07-19 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ['first_name', 'last_name'], 'verbose_name': 'Teacher', 'verbose_name_plural': 'Teachers'},
        ),
    ]
