# Generated by Django 5.2.16 on 2026-07-19 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_fix_teacher_name_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='teacher_code',
            field=models.CharField(blank=True, help_text='Short code used for login (e.g., T001). Leave blank to match by email or name.', max_length=30),
        ),
    ]
