# Generated by Django 5.2.16 on 2026-07-19 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_teacher_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='competency',
            options={'ordering': ['subject', 'form_level', 'sort_order'], 'verbose_name': 'Competency', 'verbose_name_plural': 'Competencies'},
        ),
        migrations.AddField(
            model_name='competency',
            name='form_level',
            field=models.PositiveSmallIntegerField(default=1, help_text='Form level (1-5) this competency applies to'),
        ),
        migrations.AddField(
            model_name='schoolclass',
            name='form_level',
            field=models.PositiveSmallIntegerField(default=1, help_text='Numeric form level (1=Form 1, 5=Form 5, 6=Lower Sixth, 7=Upper Sixth)'),
        ),
    ]
