# Generated by Django 5.2.16 on 2026-07-19 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_form_level'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='competency',
            unique_together={('subject', 'term', 'form_level', 'sort_order')},
        ),
    ]
