# Generated by Django 5.2.16 on 2026-07-20 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_unique_competency_sort'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='sub_division_of_origin',
            field=models.CharField(blank=True, help_text='Sub-division/Arrondissement of origin', max_length=255),
        ),
    ]
