# Generated by Django 5.2.17 on 2026-08-07 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_add_sub_division'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='teacher',
            field=models.OneToOneField(blank=True, help_text='Link to Teacher record (for teachers and class masters)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profile', to='core.teacher'),
        ),
    ]
