# Generated by Django 5.2.17 on 2026-08-07 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_userprofile_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_key', models.CharField(max_length=128, unique=True)),
                ('school_name', models.CharField(max_length=255)),
                ('max_students', models.PositiveIntegerField(default=500)),
                ('max_devices', models.PositiveSmallIntegerField(default=3)),
                ('issued_date', models.DateField(auto_now_add=True)),
                ('expires_at', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('revoked', 'Revoked')], default='active', max_length=10)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('machine_id', models.CharField(blank=True, max_length=128)),
                ('activation_count', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'License',
                'verbose_name_plural': 'Licenses',
            },
        ),
    ]
