# Generated by Django 5.2.17 on 2026-08-07 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_license'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='letterhead_line1_en',
            field=models.CharField(default='REPUBLIC OF CAMEROON', max_length=255),
        ),
        migrations.AddField(
            model_name='school',
            name='letterhead_line1_fr',
            field=models.CharField(default='REPUBLIQUE DU CAMEROUN', max_length=255),
        ),
        migrations.AddField(
            model_name='school',
            name='letterhead_line2_en',
            field=models.CharField(default='PEACE - WORK - FATHERLAND', max_length=255),
        ),
        migrations.AddField(
            model_name='school',
            name='letterhead_line2_fr',
            field=models.CharField(default='PAIX - TRAVAIL - PATRIE', max_length=255),
        ),
        migrations.AddField(
            model_name='school',
            name='letterhead_line3_en',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='school',
            name='letterhead_line3_fr',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
