# Generated by Django 5.2.17 on 2026-08-08 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_add_letterhead_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='letterhead_line1_en',
            field=models.CharField(blank=True, default='REPUBLIC OF CAMEROON', max_length=255),
        ),
        migrations.AlterField(
            model_name='school',
            name='letterhead_line1_fr',
            field=models.CharField(blank=True, default='REPUBLIQUE DU CAMEROUN', max_length=255),
        ),
        migrations.AlterField(
            model_name='school',
            name='letterhead_line2_en',
            field=models.CharField(blank=True, default='PEACE - WORK - FATHERLAND', max_length=255),
        ),
        migrations.AlterField(
            model_name='school',
            name='letterhead_line2_fr',
            field=models.CharField(blank=True, default='PAIX - TRAVAIL - PATRIE', max_length=255),
        ),
        migrations.AlterField(
            model_name='school',
            name='motto_en',
            field=models.CharField(blank=True, default='Peace - Work - Fatherland', max_length=255),
        ),
        migrations.AlterField(
            model_name='school',
            name='motto_fr',
            field=models.CharField(blank=True, default='Paix - Travail - Patrie', max_length=255),
        ),
    ]
