# Generated by Django 5.2.17 on 2026-08-13 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_backup_notifications_sms'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassCouncilRemark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_start', models.PositiveIntegerField(blank=True, null=True)),
                ('year_end', models.PositiveIntegerField(blank=True, null=True)),
                ('motif', models.TextField(blank=True)),
                ('academic_term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='class_council_remarks', to='core.academicterm')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_council_remarks', to='core.school')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_council_remarks', to='core.schoolclass')),
            ],
            options={
                'verbose_name': 'Class Council Remark',
                'verbose_name_plural': 'Class Council Remarks',
                'ordering': ['school_class__sort_order'],
            },
        ),
    ]
