# Generated by Django 5.2.17 on 2026-08-13 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_class_council_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolclass',
            name='dismissal_mark',
            field=models.FloatField(default=6.0, help_text='Annual average below which a student is dismissed at year end.'),
        ),
    ]
