# Generated by Django 5.2.17 on 2026-08-26 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_license_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='product_key',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
