# Generated by Django 5.2.17 on 2026-09-01 15:04

from django.db import migrations, models


def dedupe_current_terms(apps, schema_editor):
    """Keep only the newest current term per school before the constraint."""
    AcademicTerm = apps.get_model("core", "AcademicTerm")
    schools = set(
        AcademicTerm.objects.filter(is_current=True).values_list("school_id", flat=True)
    )
    for school_id in schools:
        current = AcademicTerm.objects.filter(
            school_id=school_id, is_current=True
        ).order_by("-year_start", "-year_end", "term_number", "-pk")
        keep = current.first()
        current.exclude(pk=keep.pk).update(is_current=False)


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_alter_license_product_key"),
    ]

    operations = [
        migrations.RunPython(dedupe_current_terms, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="academicterm",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_current", True)),
                fields=("school",),
                name="unique_current_term_per_school",
            ),
        ),
    ]
