# Generated by Django 5.2.17 on 2026-09-02 20:21

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_academicterm_unique_current_term_per_school'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('room_type', models.CharField(choices=[('classroom', 'Classroom'), ('lab', 'Laboratory'), ('workshop', 'Workshop'), ('hall', 'Hall'), ('field', 'Field / Sports Ground'), ('computer', 'Computer Room')], default='classroom', max_length=15)),
                ('capacity', models.PositiveIntegerField(default=60, help_text='Maximum student capacity.')),
                ('is_active', models.BooleanField(default=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='core.school')),
            ],
            options={
                'verbose_name': 'Room',
                'verbose_name_plural': 'Rooms',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TimetableConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year_start', models.PositiveIntegerField(help_text='e.g. 2026')),
                ('academic_year_end', models.PositiveIntegerField(help_text='e.g. 2027')),
                ('days', models.JSONField(default=list, help_text='Ordered active day names, e.g. ["Monday","Tuesday","Wednesday","Thursday","Friday"]')),
                ('assembly_day', models.CharField(default='Monday', help_text='Day of the week that has morning assembly.', max_length=15)),
                ('assembly_duration_periods', models.PositiveSmallIntegerField(default=1, help_text='How many teaching periods the assembly replaces (0 = no assembly).', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)])),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_configs', to='core.school')),
            ],
            options={
                'verbose_name': 'Timetable Config',
                'verbose_name_plural': 'Timetable Configs',
                'unique_together': {('school', 'academic_year_start', 'academic_year_end')},
            },
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Untitled', max_length=100)),
                ('status', models.CharField(choices=[('generating', 'Generating...'), ('completed', 'Completed'), ('failed', 'Failed'), ('published', 'Published')], default='generating', max_length=12)),
                ('fitness_score', models.FloatField(default=0, help_text='Solver fitness score (higher = better).')),
                ('hard_violations', models.PositiveIntegerField(default=0, help_text='Number of hard constraint violations (must be 0 for valid).')),
                ('soft_violation_count', models.PositiveIntegerField(default=0, help_text='Number of soft constraint violations.')),
                ('generation_time_seconds', models.FloatField(default=0)),
                ('solver_log', models.TextField(blank=True, help_text='Iteration details and diagnostics from the solver.')),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='core.timetableconfig')),
            ],
            options={
                'verbose_name': 'Timetable',
                'verbose_name_plural': 'Timetables',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeacherPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preference_type', models.CharField(choices=[('prefer_morning', 'Prefers morning periods'), ('prefer_afternoon', 'Prefers afternoon periods'), ('max_consecutive', 'Maximum consecutive periods'), ('free_day', 'Preferred free day (no classes)'), ('max_periods_per_day', 'Maximum periods per day'), ('min_gap_between', 'Minimum gap between lessons (periods)'), ('compact_day', 'Prefers compact day (no gaps)')], max_length=25)),
                ('value', models.JSONField(default=dict, help_text='e.g. {"max_consecutive": 4} or {"free_day": "Wednesday"}')),
                ('weight', models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='core.teacher')),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_preferences', to='core.timetableconfig')),
            ],
            options={
                'verbose_name': 'Teacher Preference',
                'verbose_name_plural': 'Teacher Preferences',
            },
        ),
        migrations.CreateModel(
            name='SubjectConstraint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('constraint_type', models.CharField(choices=[('spread_evenly', 'Spread evenly across days (no 2 periods same day)'), ('avoid_last_period', 'Avoid scheduling in the last period of the day'), ('prefer_morning', 'Prefer morning periods (first half of day)'), ('prefer_afternoon', 'Prefer afternoon periods (second half of day)'), ('not_consecutive_days', 'Avoid placing on consecutive days')], max_length=25)),
                ('value', models.JSONField(blank=True, default=dict)),
                ('weight', models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_constraints', to='core.subject')),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_constraints', to='core.timetableconfig')),
            ],
            options={
                'verbose_name': 'Subject Constraint',
                'verbose_name_plural': 'Subject Constraints',
            },
        ),
        migrations.CreateModel(
            name='PeriodSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_number', models.PositiveSmallIntegerField(help_text='Global ordering within the day (1-based, sequential).')),
                ('slot_type', models.CharField(choices=[('teaching', 'Teaching Period'), ('break', 'Break'), ('assembly', 'Assembly')], max_length=10)),
                ('label', models.CharField(help_text='Display label, e.g. "Period 1", "Morning Break", "Assembly".', max_length=50)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('can_start_double', models.BooleanField(default=False, help_text='True if a double-period lesson can START in this slot (i.e. the immediately following slot is also a teaching slot with no break in between).')),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='period_slots', to='core.timetableconfig')),
            ],
            options={
                'verbose_name': 'Period Slot',
                'verbose_name_plural': 'Period Slots',
                'ordering': ['slot_number'],
                'unique_together': {('config', 'slot_number')},
            },
        ),
        migrations.CreateModel(
            name='TeacherAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=15)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('period_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_availabilities', to='core.periodslot')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='core.teacher')),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_availabilities', to='core.timetableconfig')),
            ],
            options={
                'verbose_name': 'Teacher Unavailability',
                'verbose_name_plural': 'Teacher Unavailabilities',
                'unique_together': {('config', 'teacher', 'day', 'period_slot')},
            },
        ),
        migrations.CreateModel(
            name='SubjectPeriodRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periods_per_week', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('doubles_per_week', models.PositiveSmallIntegerField(default=0, help_text='How many of the weekly periods should be consecutive doubles (e.g. 1 means one double = 2 periods consumed, rest are singles).')),
                ('preferred_room', models.ForeignKey(blank=True, help_text='Required room (e.g. lab for Chemistry practicals).', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.room')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='period_requirements', to='core.schoolclass')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='period_requirements', to='core.subject')),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_requirements', to='core.timetableconfig')),
            ],
            options={
                'verbose_name': 'Subject Period Requirement',
                'verbose_name_plural': 'Subject Period Requirements',
                'unique_together': {('config', 'school_class', 'subject')},
            },
        ),
        migrations.CreateModel(
            name='TimetableEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=15)),
                ('is_double_start', models.BooleanField(default=False, help_text='True if this is the FIRST period of a double-period lesson.')),
                ('is_double_end', models.BooleanField(default=False, help_text='True if this is the SECOND period of a double-period lesson.')),
                ('is_locked', models.BooleanField(default=False, help_text='Locked entries are preserved during re-generation.')),
                ('period_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='core.periodslot')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timetable_entries', to='core.room')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='core.schoolclass')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='core.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='core.teacher')),
                ('timetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='core.timetable')),
            ],
            options={
                'verbose_name': 'Timetable Entry',
                'verbose_name_plural': 'Timetable Entries',
                'unique_together': {('timetable', 'day', 'period_slot', 'school_class')},
            },
        ),
    ]
